### ISSUE TITLE
further info

### ISSUE THREAD

**Issue by jontis** [julien-lang/twrp-adb-backup-extractor#1]
Great to see this project. I tried running it. 
Here's the output:

$ head -n 100 backup.ab 
TWRPtwstreamheader�G+TWRPtwfilename�h?fs�/external_sd/TWRP/BACKUPS/88f12f77/2018-01-22--10-32-14_onyx-userdebug_7.1.2_NJH47F_4cb9ee3dc1/system.ext4.winTWRPtwdatablockD���/addon.d/00407550000000000000000000000062132311571050011257xustar  rootroot50 RHT.security.selinux=u:object_r:system_file:s0
/addon.d/004075500000000000000000000000001323115710500111445ustar  rootroot/addon.d/50-cm.sh01007550000000000000000000000062111270740000012421xustar  rootroot50 RHT.security.selinux=u:object_r:system_file:s0
/addon.d/50-cm.sh010075500000000000000000000012621112707400000123140ustar  rootroot#!/sbin/sh
# 
# /system/addon.d/50-cm.sh
# During a LineageOS 14.1 upgrade, this script backs up /system/etc/hosts,
# /system is formatted and reinstalled, then the file is restored.
#

$ python extract.py -i list backup.ab 
{'type': 'twstreamheader', 'partition_count': 3, 'version': 1, 'crc': 726116382}
unknown type www.gstatic.com/
Invalid file trailer
Unable to retrieve file #0

**Comment by jontis** [comment]
Sorry bout the formatting. It's raw but github seems to misinterpret is as markdown.

**Comment by julien-lang** [comment]
Hi,

Wow, I'm amazed someone already found that. I was planning on fixing few
things and clean before communicating about it on TWRP tracker.

Anyway, the master branch contain hard-coded position about my own backup
file. So it can not really be used with another backup. But, if you
checkout the "test2" branch and add the "--auto-fix" argument, the program
should be able to list the files in your backup. Not yet able to extract
then bu I can finish that tonight :).

Let me know,

  Julien

**Comment by jontis** [comment]
Let's say I'm desperate ;-)
Broken screen but was able to adb a backup out of it. Only to find that the TWRP backup cant be extracted...

**Comment by julien-lang** [comment]
Hum, exactly the same story here. That's why I worked on this script over
the week-end. I was able to recover my files (data, system and boot), push
them on a sdcard and tell TWRP to recover from the sdcard.

My device still does not work but the system boot so I made progress...

Anyway, as I said, I will try to finish that test branch tonight so
hopefully, you can extract your files as well.

**Comment by julien-lang** [comment]
Hi @jontis, I finished my branch and merged it into master. So please try again. (use -i to be prompt to extract the files).

**Comment by jontis** [comment]
I think this worked:
 ~/tmp_backup_onyx $ ./extract.py -i list backup.ab 
{'partition_count': 3, 'type': 'twstreamheader', 'version': 1, 'crc': 726116382}
unknown type www.gstatic.com/
Invalid file trailer
unknown type 
not a control block b'\xa7\xdfh\xbc\xe1\xad\xae\xdb' b'<\x02\xf8\x01\xde\xef)\xaa/\xe9\x9b\xde\xf85\xd2\x86'
Invalid file trailer
not a control block b'\x84e\xff*-\xc8\x8bR' b'\xa5CX\xe0\x82\xee\xc5\xdc- \x08.F\xc2\x84]'
  * /external_sd/TWRP/BACKUPS/88f12f77/2018-01-22--10-32-14_onyx-userdebug_7.1.2_NJH47F_4cb9ee3dc1/system.ext4.win
     declared size: 1014.54MB (1063821312)
     real size:     978.49MB (1026018304)
     md5: d3ce0d6978a1632a86f65993ae9c98b8
     data sequence:
        1  x  1048576
        977  x  1048576
        1  x  1012224
  * /external_sd/TWRP/BACKUPS/88f12f77/2018-01-22--10-32-14_onyx-userdebug_7.1.2_NJH47F_4cb9ee3dc1/data.ext4.win
     declared size: 4.31GB (4626431017)
     real size:     4.38GB (4704456192)
     md5: bf742efca6cf5d328a9bbc817e28774a
     data sequence:
        1  x  36864
        4488  x  1048576
        1  x  709120
  * /external_sd/TWRP/BACKUPS/88f12f77/2018-01-22--10-32-14_onyx-userdebug_7.1.2_NJH47F_4cb9ee3dc1/boot.emmc.win
     size: 16.00MB (16777216)
     md5: baa544fc0f7209b3914d0be245703288
     data sequence:
        16  x  1048576
        1  x  8704

Do you want to export system.ext4.win? [Y/n]?y
  Exporting...
Do you want to export data.ext4.win? [Y/n]?y
  Exporting...
Do you want to export boot.emmc.win? [Y/n]?y
  Exporting...

**Comment by jontis** [comment]
I now have system.ext4.win and data.ext.win.
Renaming them data.ext.tar and using tar:
tar -xvf data.ext4.tar 

This got me several folders and files and some error messages:
tar: Malformed extended header: missing equal sign
tar: Removing leading `/' from member names
tar: Exiting with failure status due to previous errors

Sadly, I got many files but not the pictures I was hoping for.

**Comment by julien-lang** [comment]
Ohh, I'm happy my script worked on your backup file!

But I'm sorry it does not help you to recover your data. Pictures are usually stored in /sdcard and are not included by "adb backup". If I understand correctly, you screen does not work anymore. But can you still boot on TWRP? Like in blind mode. If so, you could adb shell/pull /sdcard no?

**Comment by elsieholmes** [comment]
So there's still no progress on this topic?

Before updating to LineageOS 15.1 I made a backup that contains a FreeOTP database I can't log in anywhere without and am pretty much desperate now. 
I can use my phone, but can't access most of my accounts :/

**Comment by julien-lang** [comment]
Hi @elsieholmes,

No, no progress since there is nothing left to do on my side. The script is completed and proved it works. I was going to close this thread.

If you have a backup and you are unable to use it, I suggest to try my script. If it does not work, please create a new ticket.
